## 45 - 1 비동기 처리를 위한 콜백 패턴의 단점

- 비동기 함수 내부 비동기로 동작하는 코드는 비동기 함수가 종료된 이후 완료
- 비동기 함수 내부의 비동기로 동작하는 코드에서 처리 결과를 외부로 반환하거나 상위 스코프의 변수에 할당하면 동작하지 않는다.
- 비동기 함수인 `setTimeout` 함수의 콜백 함수는 `setTimeout` 함수 종료 후 호출
- 비동기 함수의 처리결과(서버의 응답 등)에 대한 후속 처리는 비동기 함수 내부에서 수행해야함.
```javascript
let g = 0;

setTimeout(() => {
  g = 100;
}, 0);
console.log(g); //0
```

## 45 - 2 프로미스의 생성

```javascript
const promise = new Promise((resolve,reject)=>{
    //비동기 처리 수행
    if(/*비동기 처리 성공*/){
        resolve('result');
    }else{
        reject('failure');
    }
});
```

- 비동기 처리 성공 시 -> `resolve`함수 호출
- 비동기 처리 실패 시 -> `reject`함수 호출

| 프로미스 상태 | 의미                                  | 상태 변경 조건     |
| ------------- | ------------------------------------- | ------------------ |
| pending       | 비동기 처리가 아직 수행되지 않은 상태 | 프로미스 생성 직후 |
| fulfilled     | 비동기 처리가 성공 시                 | resolve 함수 호출  |
| rejected      | 비동기 처리가 실패 시                 | reject 함수 호출   |

- 프로미스는 비동기 처리 상태와 처리 결과를 관리하는 `객체`

## 45 - 3 프로미스의 후속 처리 메서드

- 프로미스 비동기 처리 상태가 변화하면 후속 처리 매서드에 인수로 전달한 콜백 함수가 선택적으로 호출.

### then

- 1번째 콜백 인수 : 프로미스가 `fulfilled`상태 시 호출
- 2번째 콜백 인수 : 프로미스가 `rejected`상태 시 호출

```javascript
const executor = (resolve, reject) => {
  setTimeout(() => {
    resolve("성공");
    reject("실패");
  }, 3000);
};
```

### catch

- `rejected`상태인 경우만 호출

```javascript
new Promise((_ , reject)=> reject(new Error('rejected')).catch(e=>console.log(e);))
```

### finally

- 프로미스의 성공 또는 실패와 상관없이 무조건 한 번 실행.

```javascript
new Promise(() => {}).finally(() => console.log("finally"));
```

## 45 - 4 프로미스의 에러 처리

```javascript
promiseGet("https://sfdsd.com")
  .then((res) => console.log(res))
  .catch((err) => console.error(err));
```

## 45 - 5 프로미스 체이닝

```javascript
const url = "https://jsonplaceholder";

promiseGet(`${url}/posts/1`).then(({ useId }) =>
  promiseGet(`${url}/users/${userid}`)
    .then((userInfo) => console.log(userInfo))
    .catch((err) => console.log(err))
);
```

- then : promiseGet 함수가 반환한 프로미스가 `resolve`한 값(id가 1인 post)
- then : 첫 번째 then 메서드가 반환한 프로미스가 resolve한 값(post의 userId로 취득한 user정보)
- catch : promiseGet 함수 또는 앞선 후속 처리 메서드가 반환한 프로미스가 reject한 값

## 45 - 6 프로미스의 정적 메서드

### Promise.resolve/Promise.reject

```javascript
//resolve
const resolvePromise = new Promise((resolve) => resolve([1, 2, 3]));
resolvePromise.then(console.log); //[1,2,3]
//또는
const resolvePromise = Promise.resolve([1, 2, 3]);
resolvePromise.then(console.log); //[1,2,3]

//reject
const rejectedPromise = Promise.reject(new Error("error"));
rejectedPromise.catch(console.log); //Error: error
//또는
const rejectedPromise = new Promise((_, reject) => reject(new Error("error")));
rejectedPromise.catch(console.log); //Error: error
```

### Promise.all

- 비동기 처리를 모두 병렬로 처리할 때 사용
- 모든 프로미스가 모두 `fulfilled`상태가 되면 모든 처리 결과를 저장하여 `배열`에 저장해 새로운 프로미스로 반환
- 전달받은 프로미스 객체가 하나라도 `rejected`상태이면 나머지 프로미스를 기다리지 않고 즉시 종료

```javascript
const data1 = () =>
  new Promise((resolve) => setTimeout(() => resolve(1), 3000));

const data2 = () =>
  new Promise((resolve) => setTimeout(() => resolve(2), 2000));

const data3 = () =>
  new Promise((resolve) => setTimeout(() => resolve(3), 1000));

Promise.all([data1(), data2(), data3()])
  .then(console.log) //[1,2,3] -> 약 3초 소요
  .catch(console.error);
```

### Promise.race

- 가장 먼저 `fulfilled` 상태가 된 프로미스의 결과를 `resolve`하는 새로운 프로미스 객체 반환
- 하나라도 `rejected`되면 에러를 `reject`하는 새로운 프로미스 즉시 반환

```javascript
Promise.race([
  new Promise((resolve) => setTimeout(() => resolve(1), 3000)),
  new Promise((resolve) => setTimeout(() => resolve(2), 2000)),
  new Promise((resolve) => setTimeout(() => resolve(3), 1000)),
])
  .then(console.log) //3
  .catch(console.error);
```

### Promise.allSetted

- 프로미스가 모두 `fulfilled` 또는 `rejected` 상태가 되면 처리 결과를 `배열`로 반환

```javascript
Promise.allSetted([
  new Promise((resolve) => setTimeout(() => resolve(1), 2000)),
  new Promise((_, reject) =>
    setTimeout(() => reject(new Error("error")), 1000)
  ),
]).then(console.log);

/*
[
    {status: "fulfilled",value: 1},
    {status: "rejected",reason:Error:error at <anonymous>:}    
]

*/
```

## 45 - 7 마이크로태스크 큐

- 마이크로태스크 큐는 태스크 큐보다 우선순위가 높다.

```javascript
setTimeout(() => console.log(1), 0);

Promise.resolve()
  .then(() => console.log(2))
  .then(() => console.log(3));

//출력값 2->3->1
```

## 45 - 8 fetch

- `fetch`함수는 HTTP 응답을 나타내는 Response 객체를 래핑한 `Promise` 객체로 반환
- `fetch`함수는 `404 Not Found`와 `500 Internal Server Error`같은 `HTTP에러`는 `reject`하지 않고 ok상태를 `false`로 설정한 `Response`객체를 `resolve`한다.
- 따라서 다음과 같은 방법으로 쓴다.

```javascript
const wrongUrl = "https://jsonplaceholder.com/xxx/1";

fetch(wrongUrl).then((response) => {
  if (!response.ok) throw new Error(response.statusText);
  return response.json();
})
    .then(todo=>console.log(todo))
    .catch(err=>console.error(err));
```
